# Change these first
owner: universitasdarunnajah # Your GitHub organization or username, where this repository lives
repo: online.darunnajah.ac.id # The name of this repository

sites:
  - name: Situs Web Resmi Universitas Darunnajah
    url: https://www.darunnajah.ac.id
  - name: Sistem Informasi Akademik
    url: https://simak.darunnajah.ac.id
  - name: Learning Manajemen System
    url: https://lms.darunnajah.ac.id
  - name: ParentDesk
    url: https://parentdesk.darunnajah.ac.id
  - name: StudentDesk
    url: https://studentdesk.darunnajah.ac.id
  - name: Student Cash
    url: https://tukeuangan.darunnajah.ac.id
  - name: Tracer Study
    url: https://tracerstudy.darunnajah.ac.id

  - name: Penerimaan Mahasiswa Baru
    url: https://pendaftaran.darunnajah.ac.id

  - name: SIAKAD STAI
    url: https://siakad.darunnajah.ac.id
    
  - name: e-Journal
    url: https://ejournal.darunnajah.ac.id
  - name: Repository
    url: https://repository.darunnajah.ac.id
  - name: e-Library
    url: https://e-library.darunnajah.ac.id
  - name: Sistem Informasi Bimbingan TA
    url: https://bimbingan.darunnajah.ac.id
  - name: Sistem Informasi Kuliah Kerja Nyata
    url: https://kkn.darunnajah.ac.id
  - name: Sistem Informasi LP3M
    url: https://lp3m.darunnajah.ac.id
  - name: Sistem Informasi LP3M
    url: https://monev.darunnajah.ac.id
  - name: Sistem Penjaminan Mutu
    url: https://spmi.darunnajah.ac.id
    
  - name: Pangkalan Data Pendidikan Tinggi
    url: https://neo-feederuniv.darunnajah.ac.id
  - name: Pangkalan Data Pendidikan Tinggi
    url: https://neo-feederuniv.darunnajah.ac.id

  - name: Generator Data
    url: https://generator.darunnajah.ac.id
  - name: Importer STAI
    url: https://importerstai.darunnajah.ac.id
  - name: Importer Universitas
    url: https://importeruniv.darunnajah.ac.id

  - name: Kicau Darunnajah
    url: https://kicau.darunnajah.ac.id
    
status-website:
  favicon: https://avatars.githubusercontent.com/u/119548347
  metaTags:
  #  - name: "color-scheme"
  #    content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: online.darunnajah.ac.id
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/119548347
  name: Dasbor Monitoring Sistem Informasi Universitas Darunnajah
  introTitle: "**Universitas Darunnajah** adalah lembaga pendidikan tinggi swasta yang bernaung dibawah Yayasan Darunnajah di Jakarta Selatan, Indonesia."
  introMessage: Halaman ini berfungsi untuk memonitor sistem informasi yang dimiliki Universitas Darunnajah.
  #navbar: Hapus tagar kalau mau pakai menu.
  #  - title: Monitoring
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO
      
i18n:
  activeIncidents: Insiden Aktif
  allSystemsOperational: Semua sistem beroperasi
  incidentReport: "Laporan insiden #$NUMBER →"
  activeIncidentSummary: Dibuka pada $DATE dengan $POSTS laporan
  incidentTitle: Detail Insiden $NUMBER
  incidentDetails: Detail Insiden
  incidentFixed: Diperbaiki
  incidentOngoing: Sedang berlangsung
  incidentOpenedAt: Dibuka pada
  incidentClosedAt: Ditutup pada
  incidentSubscribe: Berlangganan Pembaruan
  incidentViewOnGitHub: Lihat di GitHub
  incidentCommentSummary: Diposting pada $DATE oleh $AUTHOR
  incidentBack: ← Kembali ke semua insiden
  pastIncidents: Insiden Masa Lalu
  pastIncidentsResolved: Diselesaikan dalam $MINUTES menit dengan $POSTS laporan
  liveStatus: Status Langsung
  overallUptime: Uptime keseluruhan $UPTIME%
  overallUptimeTitle: Uptime keseluruhan
  averageResponseTime: Waktu respons rata-rata $TIMEms
  averageResponseTimeTitle: Respons rata-rata
  sevelDayResponseTime: Waktu respons 7 hari
  responseTimeMs: Waktu respons (milidetik)
  up: Aktif
  down: Non-aktif
  ms: milidetik
  loading: Memuat
  navGitHub: Kode Sumber
  footer: Dikembangkan oleh [Faishal Wafiq Zakiy](https://www.zakiy.my.id) untuk [Universitas Darunanjah](https://www.darunnajah.ac.id).
  rateLimitExceededTitle: Batas permintaan terlampaui
  rateLimitExceededIntro: Anda telah melebihi jumlah permintaan yang dapat Anda lakukan dalam satu jam, jadi Anda harus menunggu sebelum mengakses situs web ini lagi. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub untuk terus menggunakan situs web ini.
  rateLimitExceededWhatDoesErrorMean: Apa arti kesalahan ini?
  rateLimitExceededErrorMeaning: Situs web ini menggunakan API GitHub untuk mengakses data waktu nyata tentang status situs web kami. Secara default, GitHub mengizinkan setiap alamat IP 60 permintaan per jam, yang telah Anda gunakan.
  rateLimitExceededErrorHowCanFix: Bagaimana cara memperbaikinya?
  rateLimitExceededErrorFix: Anda dapat menunggu satu jam lagi dan batas alamat IP Anda akan dipulihkan. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub Anda, yang memberi Anda 5.000 permintaan tambahan per jam.
  rateLimitExceededGeneratePAT: Pelajari cara membuat Token Akses Pribadi
  rateLimitExceededHasSet: Anda memiliki set token akses pribadi.
  rateLimitExceededRemoveToken: Hapus token
  rateLimitExceededGitHubPAT: Token Akses Pribadi GitHub
  rateLimitExceededCopyPastePAT: Salin dan tempel token Anda
  rateLimitExceededSaveToken: Simpan token
  errorTitle: Terjadi kesalahan
  errorIntro: Terjadi kesalahan saat mencoba mendapatkan detail status terbaru.
  errorText: Anda dapat mencoba lagi dalam beberapa saat.
  errorHome: Buka beranda
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
